### ISSUE TITLE
Allow to easily override or style directly the different info types and with/without rich colors enabled

### ISSUE THREAD

**Issue by dez1729** [tutkli/ngx-sonner#9]
### Information

Allow the styles for different types (info, errors, etc.) to be overridden. 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by tutkli** [comment]
Hello @dez1729 ! You can easily override the styles of different types of toast using the `data-type` attribute, and works with every type of toast, for example:

Create your custom class:
```css
.custom-info[data-sonner-toast][data-type='info'] {
  background-color: lightblue;
  color: black;
  border: 2px solid black;
}
```
You can use this class per toast:
```ts
toast.info('My custom info toast', {
  class: 'custom-info'
}
```
Or, globally in the toaster:
```html
<ngx-sonner-toaster [toastOptions]="{ class: 'custom-info' }" />
```

Also, you can override styles with the toastOptions `classes` field, works for both toaster and toast fn: 

```ts
customClasses: ToastClassnames = {
    info: 'custom-info',
    warning: 'custom-warning',
    success: 'custom-success',
    error: 'custom-error',
  }

<ngx-sonner-toaster [toastOptions]="{ classes: customClasses }" />

toast('Hello world', { classes: customClasses });
}
```
